all: A2_sort A2_grep1 A2_grep2

sort: A2_sort.c
	gcc -o -Wall -pedantic A2_sort A2_sort.c

grep1: A2_grep1.c
	gcc -o -Wall -pedantic A2_grep1 A2_grep1.c

grep2: A2_grep2.c
	gcc -o -Wall -pedantic A2_grep2 A2_grep2.c
